### ISSUE TITLE
Switching to Groovy compiler 2.4.1.xx-201502281941-e44 does not work

### ISSUE THREAD

**Issue by sboekhoff** [groovy/groovy-eclipse#112]
I installed the snapshot of the groovy-eclipse plugin (https://github.com/groovy/groovy-eclipse/wiki) using the update-site http://dist.springsource.org/snapshot/GRECLIPSE/e4.4/ . Switching between the groovy-compiler-versions `2.2.2.xx` and `2.3.10.xx` works fine:

![s1](https://cloud.githubusercontent.com/assets/10683690/6784601/e68da9f4-d180-11e4-800d-d06559bf626f.png)

![s2](https://cloud.githubusercontent.com/assets/10683690/6784602/e690c58a-d180-11e4-915f-e4253c6b30d5.png)

I also tried to switch to version `2.4.1.xx`. But after restarting, the compiler-version was the same as before.
Switching the compiler to `2.4.1` on a project-level does not work, since there is no option for that version:

![s3_2](https://cloud.githubusercontent.com/assets/10683690/6784780/046c7666-d182-11e4-93e3-c4566955e107.png)

My Eclipse (running on `Ubuntu Linux 14.10`):
`Version: Luna Service Release 2 (4.4.2)`
`Build id: 20150219-0600`

**Comment by BoykoAlex** [comment]
Should be fixed now. Please install the latest Groovy Eclipse from http://dist.springsource.org/snapshot/GRECLIPSE/e4.4 <http://dist.springsource.org/snapshot/GRECLIPSE/e4.4> (or e4.5 at the end.. whatever corresponds to your version of Eclipse)
I’ve built Groovy-Eclipse locally and installed from the local update site into Eclipse and confirmed that the fix is working. However, the build hasn’t completed yet, it’s queued. I’ll let you know when the build is available.

**Comment by BoykoAlex** [comment]
The build is ready. Update site: http://dist.springsource.org/snapshot/GRECLIPSE/e4.4

**Comment by sboekhoff** [comment]
Now it works, thanks.
