### ISSUE TITLE
Non-cosmetic failures using @TupleConstructor on nested class

### ISSUE THREAD

**Issue by chrylis** [groovy/groovy-eclipse#1216]
Groovy-Eclipse sometimes drops spurious errors in the editor saying that a constructor added by `@TupleConstructor` can't be found, but these are generally cosmetic and don't result in actual compilation errors (i.e., no markers, code runs).

However, I've discovered that as of 3.0.7 having a static nested class (a record for a command type) annotated with `@TupleConstructor` causes actual errors using the Groovy-Eclipse compiler; the previous false alarm does generate a marker and a failing class file. A full clean and build, which usually handles mismatches because everything's available, doesn't help. `mvn compile` with groovyc works fine.

**Comment by eric-milles** [comment]
I would need an example project to take this further.  In general, the transforms that add members to a class that are not already represented by an interface of Object (`TupleConstructor` vs `ToString`) are not processed for source references.  Example, class A has reference to class B.  When compiling class A, the reference to B is resolved by processing class B as far as conversion.  B is not fully processed because it may contain a direct or indirect reference to class A.  This is discussed further in #704 and others.

**Comment by chrylis** [comment]
Replicable. In order to reproduce:
- nested class; inner or static does not matter
- the client class must be `@CompileStatic` (the error is actually produced by the STC)

```groovy
class Outer {
    @TupleConstructor(defaults = false)
    static class Nested {
        String value
    }
}

@CompileStatic
class Client {
    void foo() {
        new Nested('123')
    }
}
```

**Comment by eric-milles** [comment]
Is this limited to when `Outer` and `Client` are in the same source file?

**Comment by eric-milles** [comment]
ready to test
