### ISSUE TITLE
Eclipse Marketplace Error

### ISSUE THREAD

**Issue by AlanKavo92** [groovy/groovy-eclipse#1218]
I am trying to install Groovy Development Tools on  2019-09 (4.13) and I am receiving "Received fatal alert: handshake_failure"

I have just checked the health check and it seems all but Juno have an error beside them:
https://www.eclipse.org/setups/marketplace/?id=321859

```
Unable to read repository at https://dist.springsource.org/release/GRECLIPSE/4.0.0/e4.13/content.xml.
Unable to read repository at https://dist.springsource.org/release/GRECLIPSE/4.0.0/e4.13/content.xml.
Received fatal alert: handshake_failure
```

**Comment by AlanKavo92** [comment]
@eric-milles

**Comment by eric-milles** [comment]
If you look into the details of the error, they are showing a failure to complete installation because the JDT is not found.  This is a requirement of GDT.
```
Missing requirement: Eclipse JDT Core patch for Groovy 4.0.0.v202012311604-e1909-RELEASE (org.codehaus.groovy.jdt.patch.feature.group 4.0.0.v202012311604-e1909-RELEASE) requires 'org.eclipse.equinox.p2.iu; org.eclipse.jdt.feature.group [3.18.100.v20190916-1045,3.18.100.v20190916-1045]' but it could not be found
```

The update sites at springsource are using fairly new https config and you should have a current Java 8 or better install to be able to process the security credentials.
