### ISSUE TITLE
Eclipse ignores Groovy sources in src/main/java in Maven project

### ISSUE THREAD

**Issue by davidmichaelkarr** [groovy/groovy-eclipse#1259]
I'm trying to get a project that uses Groovy to work in Eclipse.  I'm using Eclipse 2021-03, and 4.1.0.v202103311613-e2103-RELEASE of Groovy Eclipse.

The project has Groovy source files in src/main/java.  I don't know if this is a problem or not. I would think that is ok.

I have the project set to use the 2.5 compiler.

The Maven command line build works fine. Eclipse complains that those Groovy classes "... cannot be resolved to a type".  If I enter the class name in "Open Type", it IS able to find it, and I can find it in the "src/main/java" source repository in the package explorer. If I look for the class file in the filesystem, I find it in both the "target" and "bin" subdirs, but Eclipse still says it can't find that type.

I've tried doing a "Project Clean" and a "Maven Update".  Neither makes a difference.

Another colleague who has worked on this project said that he thinks he was getting this kind of problem before he switched from Eclipse to SpringToolSuite.  He's trying to remember if he did anything else to fix it.

Not sure what else to try here.

**Comment by davidmichaelkarr** [comment]
Ok, so I got past one problem, only to hit a problem I've seen before, and still don't have a resolution for.

I noticed in the Build Path in the project, it was only including "**/*.java".  I added "**/*.groovy" and that finally made those missing classes available.  I guess we wouldn't have had this problem if we had put them in "src/main/groovy", assuming no other unintended consequences.

However, after fixing that, I'm now back to this problem: https://github.com/groovy/groovy-eclipse/issues/893 .  When I ran into this before, it was on a project that was somewhat optional for me.  Now, I really have to get this working.  It's not clear to me whether I can even install an older version of the plugin.  I tried installing the version associated with 2020-12, but it simply wouldn't let me, and updated the installation to get the 2021-03 version.  I'd prefer not to have to change the project (the solution involving creating that missing class).

**Comment by eric-milles** [comment]
It would help greatly to see what your project looks like.  A quick screenshot to see how it appears in the Package Explorer with relevant nodes expanded and include here your pom.xml (excerpt) and .classpath files.  I don't know what "it was only including '/*.java'. I added '/*.groovy'" refers to.  Did you import your project and have eclipse create its metadata or did you create it (.classpath, .protect, .settings, ...) separately?  Your reference seems to imply that you have a Groovy 2.4 dependency but you have only mentioned Groovy 2.5.  Eclipse-Maven integration is more easily troubleshooted if I had access to your project; I;m guessing that may not be possible.

**Comment by davidmichaelkarr** [comment]
I don't know what nodes would be relevant:
![image](https://user-images.githubusercontent.com/5566419/119085144-ffff3080-b9b7-11eb-95c4-f86ee51b4339.png)

When I say "it was only including "/*.java", I had added two asterisks at the start of that, but I guess that was markdown magic, so it ate them.

This is what it looks like now:
![image](https://user-images.githubusercontent.com/5566419/119085248-389f0a00-b9b8-11eb-890f-2d4547bf18f3.png)

I had imported the project from my git repository, but Eclipse didn't do a good job of figuring it out (it didn't guess that src/main/java was a source directory), so I punted to "mvn eclipse:eclipse" (I've heard that is obsolete, but it seems to get close).

I don't know why you think there is a Groovy 2.4 dependency.

I can provide other details of the project, but providing the entire project won't be possible.

**Comment by eric-milles** [comment]
It looks like the project is missing the Groovy nature.  Usually it would have a "G" instead of a "J" in the upper right.  You can confirm this in the Project Natures property group under project properties.  And you can add from there if it is missing.  Or you can do "Groovy > Add Groovy nature to project" under the project context menu.

For "src/main/java" in Java Build Path, you can clear all includes and excludes so that it states "Included: (All)" and "Excluded: (None)".  For "src/test/java" and "src/test/resources", you can set "Contains test sources" to yes.  And make sure the includes and excludes are cleared as well.  Also, I have output set to "bin/main" and "bin/test" for main and test sources respectively.  This keeps them separated.  To make this work I set a default output folder that is not just "bin".

![image](https://user-images.githubusercontent.com/18193802/119132075-dd910580-b9ff-11eb-8a0e-7db09e98cf8a.png)

Can you expand Referenced Libraries?  I'm wondering what Groovy libraries are included by your pom and what their maven scope is set to.

And you can do "Groovy > Add Groovy DSL Support to classpath" if you want -- if you make use of transforms that the DSLDs would help with in the editor.


Normally, the m2e support would do a lot of this for you, but I don't know what is in your pom, so I don't know what could be auto-detected.  "mvn eclipse" can do this too, but it probably needs a bunch of additional xml to add natures, set test attributes, etc.

**Comment by eric-milles** [comment]
If you don't need the stuff in "opt/ajsc/etc/config" available from your classpath, you can remove that source folder.  Not sure what else is in the "src" and "opt" folders.  You may be good to go there.

**Comment by davidmichaelkarr** [comment]
To be clear, the main concern I have right now is the error I get after fixing the build path, the complaint about "groovy.transform.Generated".

The project already had the Groovy nature, and opt/ajsc/etc/config is required in the classpath.

When I expand referenced libraries, it shows that I'm using the following:
![image](https://user-images.githubusercontent.com/5566419/119159629-48e0d480-ba0c-11eb-8a25-0f18b38a8e88.png)

That certainly might conflict with the compiler I'm trying to use.  Those versions are defined in our parent pom.  Is my problem with "groovy.transform.Generated" because that is defined in the 2.5 artifacts, not 2.4?

**Comment by eric-milles** [comment]
Yes, if you have Groovy Compiler 2.5 and your project provides Groovy Runtime 2.4, you will have #893 (missing Generated annotation) to deal with.  You can update the dependencies of your project to Groovy 2.5 or provide a definition for Generated or go back to Greclipse 3.9.0.  Much more discussion under the linked issue.

Also, if you have "groovy-all" you don't need "groovy", "groovy-xml", "groovy-json", etc.  That is just one more source of mismatched version issues.
