### ISSUE TITLE
Why are releases not synced to Maven Central?

### ISSUE THREAD

**Issue by cstamas** [groovy/groovy-eclipse#1359]
Wiki mentions that "many versions are available from Central", and latest are on given repo. But this seems stale, as last releases on Central are more than a year old.

Why is the project not syncing to Maven Central?

**Comment by johanhaleby** [comment]
I wonder the same thing. The latest version in maven central doesn't seem to support Java 17, whereas the latest in the custom repo does. It would be great if you could upload the latest release to central as well. I really want to use this compiler the in [rest-assured](https://rest-assured.io/) project. Let me know if there's anything I can do to help.

**Comment by johanhaleby** [comment]
@eric-milles That's a shame :( So there probably won't be any more releases to central? If that's the case I might consider forking the project and pushing it to maven central under a different groupId.

**Comment by cstamas** [comment]
This is very sad indeed. The server wiki points to, is regularly up and down, for example right now is down :disappointed:  

https://groovy.jfrog.io/artifactory/plugins-release 

I mean, this simply prevents people accessing the artifacts (unless they build it from sources themselves). Also, as I saw (rare occasion when server was up), it contains many things, not **only groovy-eclipse, it is more a mixed bag of artifacts**. So, making Maven users of groovy-eclipse to proxy this for groovy-eclipse artifacts is just non-acceptable IMHO.

Do you need a help to fix your build? IMHO to make artifacts accessible from Maven Central should be considered mandatory, especially as service where you publish to is so unstable...

**Comment by kwin** [comment]
Can’t you use https://central.sonatype.org/publish/publish-guide/ for publishing?

**Comment by eric-milles** [comment]
> [https://groovy.jfrog.io/artifactory/plugins-release] contains many things, not only groovy-eclipse, it is more a mixed bag of artifacts

@cstamas You can use `plugins-release-local` which only contains the groovy-eclipse artifacts at the moment.

> The server wiki points to, is regularly up and down

The outage is the first that I am aware of.  It is unfortunate, but if you have a cached artifact, your build continues to run.


Maven Central publication was stopped when Pivotal orphaned the project.  It took much effort to get the batch compiler build updated enough to meet the new requirements of Maven Central.  And Bintray was extremely helpful in providing a manual process for publishing artifacts.  When Bintray was decommissioned it again required much effort to find a repository for the artifacts and understand the process for publishing.

Without Bintray in the picture, I would need to develop processes for artifact signing and publishing.  I thought that getting the artifacts to a location that was stable and reachable would be sufficient.  It is difficult for me to dedicate my volunteer efforts to devops when I much prefer to fix bugs and make enhancements to Groovy and Groovy-Eclipse.  BTW, I'm also being asked by Pivotal/VMWare to move the builds off their infrastructure. So yay... more devops.

If someone is willing to help set up some kind of process that will publish to Maven Central once I upload artifacts to [Artifactory](https://groovy.jfrog.io/artifactory/plugins-release-local), I'd love to hear from you.

**Comment by kwin** [comment]
For hosting the p2 site you can use GH Pages (https://www.lorenzobettini.it/2021/03/publishing-an-eclipse-p2-composite-repository-on-github-pages/) and for Maven Artifacts OSSRH. Both together can be used as replacement of Bintray and should be pretty sustainable.

**Comment by jdillon** [comment]
Curious have you considered donating this to Apache (and let their infra and the Core Groovy team maintain) or is that a non-starter due to the use of Eclipse?

Otherwise, signing artifacts is fairly simple (though I admit the process is a bit annoying).  The maven-release-plugin and the maven-gpg-plugin do however work fairly well in this respect, as does the nexus-staging-maven-plugin for upload to OSSRH for publishing to Maven Central.

Just a thought, but perhaps a small specifically crafted Maven project that using something like the build-helper-maven-plugin, to attach pre-built jars, sources and javadocs, sign and upload might be a reasonable solution given the complexity of how this project builds presently?   Since the dependencies of the compiler and batch modules are fairly simple, this may be a suitable if not preferred option to consider.

While I can (and do) appreciate "getting the artifacts to a location that was stable and reachable", w/o these in Maven Central there are other hurtles that users need to potentially go through to be granted access to use a non-standard repository, which puts a strong barrier up for users to consume the latest version of this integration.

The Maven Central team at Sonatype might also have some other short-term options to help if you reach out and ask for some help via JIRA ( https://central.sonatype.org/publish/publish-guide/ ).

**Comment by eric-milles** [comment]
Full disclosure, I am a member of the Apache Groovy PMC.  There is no team to take this on -- the PMC includes only 1 paid (half-time) member.  What we have discussed is adding jobs/scripts to Artifactory (groovy.jfrog.io) so that once `groovy-eclipse-batch` or `groovy-eclipse-compiler` is published, we can sign and push to Maven Central after a grace/testing period.  This is what Bintray once did for us.

**Comment by jdillon** [comment]
`adding jobs/scripts to Artifactory (groovy.jfrog.io) so that once groovy-eclipse-batch or groovy-eclipse-compiler is published` sounds good enough to me :-)

**Comment by venkatrao225** [comment]
@eric-milles I am interested to contribute `jobs/scripts`. Can you guide me on this? I want to connect with you offline to discuss in more detail.
