### ISSUE TITLE
Update site for eclipse 4.5 doesn't work

### ISSUE THREAD

**Issue by AlexLuya** [groovy/groovy-eclipse#137]
Hello,
       Accessing this http://dist.springsource.org/snapshot/GRECLIPSE/e4.5/ got errors:

```
     "can not find : http://dist.springsource.org/snapshot/GRECLIPSE/e4.5/"
```

**Comment by AlexLuya** [comment]
Now got another error:

````java
An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Unable to read repository at http://dist.springsource.org/snapshot/GRECLIPSE/e4.5/plugins/org.codehaus.groovy_2.3.10.xx-201508121448-e45.jar.
No route to host
````

**Comment by pope12389** [comment]
also got a problem:

Cannot complete the install because one or more required items could not be found.
  Software being installed: Groovy-Eclipse Feature 2.9.2.xx-201508121448-e45 (org.codehaus.groovy.eclipse.feature.feature.group 2.9.2.xx-201508121448-e45)
  Missing requirement: Groovy-Eclipse Feature 2.9.2.xx-201508121448-e45 (org.codehaus.groovy.eclipse.feature.feature.group 2.9.2.xx-201508121448-e45) requires 'org.codehaus.groovy.compilerless.feature.feature.group [2.9.2.xx-201508121448-e45]' but it could not be found

**Comment by mustangxu** [comment]
I got a "There are no items available" message for http://dist.springsource.org/snapshot/GRECLIPSE/e4.5/

<img width="856" alt="install" src="https://cloud.githubusercontent.com/assets/194269/10726341/0577c840-7c0d-11e5-977c-1b17baa3b0ff.png">

**Comment by mustangxu** [comment]
Any update for this issue? I cannot install greclipse on 4.5 mars

**Comment by dongshen** [comment]
any updated on this issue?

**Comment by missedone** [comment]
the update site for e4.5 works, i just installed groovy-eclipse through it.

**Comment by Mutley5000** [comment]
It seems this repository is not available?

**Comment by erkinalp** [comment]
Still no avail.

**Comment by Mutley5000** [comment]
It seems my problem was using my company's proxy.  I have resolved this issue.  Thanks.

**Comment by AndyWu2015** [comment]
my suggestion is to go to your {user.home}/.eclipse/org.eclipse.oomph.p2/cache to clean all the cache and install again , this may helps

**Comment by amolanil1234** [comment]
Check your proxy is not blocking the connection to external servers .
