### ISSUE TITLE
ClassCastException at runtime in with closure

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#1412]
I have an inconsistent behaviour with code like this.

```java
package testcce;
public class TestCce {
	public static void main(String[] args) {
		final Foo f = new Foo();
		f.foobar();
		f.getBar().setBar("aaa");
	}
}
```

```groovy
package testcce
import groovy.beans.Bindable
import groovy.transform.CompileStatic
@CompileStatic
class Bar {
	@Bindable
	String bar
	String other
}
```

```groovy
package testcce
import groovy.beans.Bindable
import groovy.transform.CompileStatic
@CompileStatic
class Foo {
	Bar bar
	@Bindable
	String foo
	
	void foobar() {
		bar = new Bar()
		bar.with {
			addPropertyChangeListener('bar') {
				other = 'something'
				println 'ok'
			}
		}
		println 'end'
	}
}
```

If I run this from Eclipse (using Greclipse 4.8.0.v202210232216-e2206) I get the following `ClassCastException`:

```
Exception in thread "main" java.lang.ClassCastException: class testcce.Foo cannot be cast to class testcce.Bar (testcce.Foo and testcce.Bar are in unnamed module of loader 'app')
	at testcce.Foo$_foobar_closure1$_closure2.doCall(Foo.groovy:14)
```

If I compile and run this with Gradle/groovyc (with Groovy 2.5.19), all works fine.
What is really strange is that this is just a test case I could extract from my real project. With my real project I see the exact same exception even if I compile it with Gradle and run the application under Tomcat in the test and production environments.

A workaround is to add `@CompileDynamic` to `Foo.foobar()`.

**Comment by mauromol** [comment]
Please note this problem exists at least since 2.5.13.

**Comment by eric-milles** [comment]
I was just looking at this sort of thing over the weekend.  Your deepest closure block has "owner" the `with` closure, "owner.delegate" `Bar` and "owner.owner" `Foo`.  The implicit-this calls to `addPropertyChangeListener`, `setOther` and `println` require some precise handling in the static compiler.  "other = 'something'" is converted to "this.other = 'something'" with metadata "owner.delegate" for "this".  Then the class generator converts it to "this.getOwner().getDelegate().setOther('something')" and there are check-casts for each path element.

If the latest snapshot still has a problem with this after the [GROOVY-9089](https://issues.apache.org/jira/browse/GROOVY-9089) fix, you can write "owner.delegate.other = 'something'" and "this.println('ok')" to make it explicit instead of dynamic compilation.

**Comment by mauromol** [comment]
Hi Eric,
sorry, I'm not sure I understand what I should test. Do I have to update Greclipse to the latest snapshot? It is enough?
Is there a bug in Groovy as well? The mentioned GROOVY-9089 seems to be fixed in Groovy 2.5.7, so long time ago.

**Comment by eric-milles** [comment]
The latest snapshot includes a fix for 9089, which I discovered over the weekend had regressed.  I cannot recreate your issue with current code unless I'm missing something.

**Comment by mauromol** [comment]
Indeed, this seems to work when running the code from Eclipse with Greclipse 4.8.0.v202210241547-e2206. However, how is this supposed to go into Groovy? GROOVY-9089 is still closed. Should we open a new issue for Groovy or do you plan to reopen GROOVY-9089?

**Comment by eric-milles** [comment]
The fix for 9089 went into the main project at the same time.  It will be in the next Groovy 2.5, 3.0 and 4.0 releases.
