### ISSUE TITLE
Groovy Development Tools keeps resetting the Eclipse preference Java/compiler/building/build path problems/incompatible required binaries to Error

### ISSUE THREAD

**Issue by marioja** [groovy/groovy-eclipse#1541]
If I open an Eclipse workspace with Eclipse 2023-12 that contains a maven jar project, set the incompatible required binaries setting to ignore, then after restarting Eclipse and opening the same workspace, as soon as I click in the Java Enterprise Explorer the java project to open the tree view, the required binaries settings is reset to error.  This only occurs if the groovy development tools 4.0 and 5.0 compiler features are included in the Eclipse installation.

**Comment by eric-milles** [comment]
Are there any errors in you Error Log view that indicate a problem saving the preference?

**Comment by marioja** [comment]
no.  The preference is save correctly.  Here is the use case.

1. I set the incompatible required binaries to ignore.
2. I restart Eclipse
3. I check the incompatible required binaries setting: still set to ignore
4. I expand a java project in the enterprise explorer view
5. Errors appear in the problem view about incompatible binaries
6. I look at the incompatible required binaries settings: it is now set back to error

**Comment by eric-milles** [comment]
Ahh yes, so the use case was this:  Groovy 5 raised the minimum Java version to 11.  If you worked with a project that is set to target less than that, the compiler will not be able to generate bytecode in compliance with your target level (say 8).  I wanted to see something at compile time instead of having an error at runtime for unsupported class files.

https://github.com/groovy/groovy-eclipse/blob/11cfde70dbdeb379f355754b534f076a8b388b96/base/org.eclipse.jdt.groovy.core/src/org/codehaus/jdt/groovy/integration/internal/GroovyLanguageSupport.java#L291

What so you have your Java `source` and `target` or `release` level set to for your project?

**Comment by marioja** [comment]
source and target were set to java 8

**Comment by marioja** [comment]
I think the problem may occur even if it is set to java 17 (source and target) but I am not 100% sure.

**Comment by eric-milles** [comment]
Groovy 5 compiler is not capable of producing compatible class files for a Java 8 target.  The error is enabled on so you don't find that out when running.  Groovy 4 can target Java 8 so the setting should stay the way you put it.

If you set your project's source and target level to 11 or higher, the preference will not get changed.  The check in the linked code compares your project setting, which can be anywhere from Java 1.3 to Java 21 to the value that the Groovy compiler picked up.

This is new to Groovy 5 since it is the first release to drop the old jvm target levels (aka 1.3 to 10) and require Java 11 as a minimum.
