### ISSUE TITLE
Helping the project?

### ISSUE THREAD

**Issue by chrylis** [groovy/groovy-eclipse#171]
I'm a confirmed polyglot Java/Groovy user, and I have a distinct preference for Eclipse (STS) for my development work. As there's no longer support from Pivotal and it looks like the previous maintainers are low on bandwidth, I'd be interested in learning how to perform the project maintenance at least to the extent of keeping basic compiler functionality up to date with GRECLIPSE, and possibly looking at improvements such as cutting everything over to indy (since at this point even Java 7 is EOL). I'm not sure where to start--even for building Eclipse plugins--but would like to find out more.

**Comment by aclement** [comment]
Hey. I thought we had instructions for getting a dev environment setup for groovy-eclipse but I can't find them on this wiki. This is an old set: https://web.archive.org/web/20150102210202/http://groovy.codehaus.org/Getting+Started+With+Groovy-Eclipse+Source+Code#GettingStartedWithGroovy-EclipseSourceCode-ImportGroovy-Eclipsesourcecodeintoyourworkspac

One useful task would therefore be to contribute a real wiki page here that encapsulates an up to date version of that information for yourself and other people wanting to contribute. Once that is setup you can just follow these instructions to update groovy:

https://github.com/groovy/groovy-eclipse/wiki/Updating-the-groovy-in-groovy-eclipse

And going with an indy variant, I don't especially see a problem with that. You might annoy those who can't get onto Java8 yet but I suppose they could stick to an old compiler.

**Comment by chrylis** [comment]
Indy support was added in Java 7. Anybody who's still using Java 6... well.

**Comment by aclement** [comment]
Ah, you are right, of course it was, I was thinking lambdas use it but of course they came later and exploited what was already in the JDK since 7.

**Comment by felixdo** [comment]
How about we add a setup for groovy-eclipse to eclipses oomph catalog?

**Comment by eric-milles** [comment]
I too would like to help out to get some of the issues we have encountered fixed and deployed.  I believe I have gotten to the point where the projects build and the tests run.  There are tons of warnings and inconsistent project preference settings.  This should be an easy thing to start rectifying before upping the min execution environments to 1.7 or flipping over to indy variants.

**Comment by effrafax** [comment]
Hi, I am willing to help out too. Setting up the development environment for proper build is a hard task. Maybe we can exchange our experiences to get a common base. I think it would be easier if there is something like a forum, mailing list or whatever where we can communicate about it. The github issue comments are not really the right place for this. Any suggestions?

**Comment by hammenb** [comment]
@aclement 
> I thought we had instructions for getting a dev environment setup for groovy-eclipse but I can't find them on this wiki. One useful task would therefore be to contribute a real wiki page here that encapsulates an up to date version of that information for yourself and other people wanting to contribute.

I've done this, but do not seem to have permission to push these changes back to the wiki.  Here is a link to the updated page in my clone of the wiki:

https://github.com/hammenb/groovy-eclipse-wiki/blob/master/Getting-Started-with-Groovy-Eclipse-Source-Code.md

Please review.  I will be happy to make any requested changes or additions.

**Comment by eric-milles** [comment]
There are directions: https://github.com/groovy/groovy-eclipse/blob/master/docs/IntroductiontoGroovy-EclipseDev.pdf

I don't know how up-to-date they are.

However, after following them as best I could, I ended up with an Eclipse PDE setup that I thought was correct.  However, many of the tests failed.  So I needed some kind of statement that noted which tests will fail or that all tests should pass and if some don't you must have an incorrect setup.  Basically, I didn't know where to go from where I got to.

I tried Eclipse Mars, Luna, and Juno and all had the same result.  If someone could help me get to a certified correct state, I could reverse all the directions and make corrections or add details where I found there were leaps of understanding that needed to be made.

**Comment by felixdo** [comment]
There is another Ticket about using oomph/Eclipse Installer to setup a Dev
env. I will try to fix that very soon. About the Tests i have no clue.
Somewhere in the Wiki there is a link to the build Server and from there it
seems Tests are not being run at all for the official Builds...

Il 15/ago/2016 16:48, "Eric Milles" <notifications@github.com> ha scritto:

**Comment by eric-milles** [comment]
@hammenb Thanks for the updated instructions.  I am going to run through them today and see where I can get to.

@felixdo Re: Tests.  It's fine if the tests aren't all passing as long as I can be informed what a correct state looks like.  From there I could make changes to fix tests.  As of now, I have no confidence in making any changes.  But I'd very much like to fix things.

**Comment by hammenb** [comment]
@eric-milles
>There are directions: https://github.com/groovy/groovy-eclipse/blob/master/docs/IntroductiontoGroovy-EclipseDev.pdf

If you look at the commit message for my changes, it states that this PDF is where most of the content originated from, so these are basically the same directions--just updated.  I think the PDF should eventually be removed because 1) it's outdated and 2) a markdown file is much easier to update and DIFF than a PDF.

@felixdo 
> ..it seems Tests are not being run at all for the official Builds...

Agreed.  Here is the link to the CI builds status: https://build.spring.io/browse/GRECLIPSE.  You'll see the "No tests found" message appear next to the recent releases.  The tests have been getting skipped.

Using Maven or Eclipse everything builds--[except for one trivial problem in Eclipse](https://github.com/groovy/groovy-eclipse/issues/194), but not all tests pass.  Tickets will need to be created to address the problems with the tests.  I plan to look into that next.

> There is another Ticket about using oomph/Eclipse Installer to setup a Dev env.

Excellent! That will greatly simplify things.  (Documentation for manual setup should probably still always be retained, because it will sort of inform how Oomph is setup for this project, and how to set things up if the Oomph setup ever happens to be broken or out-of-date.)

**Comment by aclement** [comment]
@hammenb Good work on migrating from pdf to markdown. Much easier to work with - something we didn't have time to do. Can you submit that as a PR against the wiki?

Re: the builds. Yes, tests are turned off because no-one has any time to maintain them. Since you guys are looking to turn things around I've just re-enabled the tests and kicked off a build: https://build.spring.io/browse/GRECLIPSE-GE46-9 - the result should give a better picture of the state of things. It is not uncommon for tests to fail on the build machine but work locally - that is really annoying.

**Comment by eric-milles** [comment]
@hammenb

When I get to importing the projects, can I select the smaller set of projects here, instead of importing them all the closing many of them?  (That is how it appears in the PDF.)  In the PDF, it shows getting all of the org.codehaus.groovyXX projects.

Are the Feature projects necessary?  Is org.codehaus.groovy.eclipse.pluginbuilder needed?  It does not have any sources and appears to be missing recent eclipse versions.

Note: You list the quickFix project twice.

The org.codehaus.groovy.eclipse.codeassist.completion.test and org.codehaus.groovy.eclipse.codebrowsing.test do not target a specific JRE container.  This is probably why there is a step in the PDF to set Java 7 as your default.  Should these projects target JavaSE-1.7?

org.eclipse.jdt.groovy.core.tests.compiler targets J2SE-1.4; should this be 1.5, 1.6 or 1.7?


When I get the projects and build, I have lots of warnings (something I'd like to fix) and 9 errors.  There are cases where non-Java5 APIs are used in projects that target J2SE-1.5.  Here is a patch for that:
[groovy-eclipse-jdk5.patch.txt](https://github.com/groovy/groovy-eclipse/files/418558/groovy-eclipse-jdk5.patch.txt)

**Comment by hammenb** [comment]
@aclement 
>Can you submit that as a PR against the wiki?

Actually, I don't think so.  There is no option for that, and everything I read says that Github does *not* support forks and pull requests for their wikis.  If you want to make it so that we can do pull requests on the documentation, it might be better to move everything in the wiki into the /docs folder of the project, and have the wiki contain nothing but a link to that.  ([That is the approach the Gradle project uses](https://github.com/gradle/gradle/wiki).)  That would also make it easier to get the "in-sync" documentation that correlates to any older commits that someone might check out.

Long-term, we could maybe use Mylyn Wikitext to contribute a "developer guide" and/or a "user guide" to the Eclipse Help Contents (similar to what JDT, EGit, etc... have).  I think having the wiki in the same repo as the project is also preferable for repeatable builds if we ever want to do this.

**Comment by hammenb** [comment]
@eric-milles I will try to do some cleanup and make clarifications based on your feedback later tonight.  I will report back when that's available.

> There are cases where non-Java5 APIs are used in projects that target J2SE-1.5.

I created a Github issue for these errors last night: https://github.com/groovy/groovy-eclipse/issues/194.

**Comment by eric-milles** [comment]
I now have these projects in my workspace, plus the very minor changes to support JDK5.  I also set Window > Preferences > Compiler > JDK Compliance to 1.7.  They build with no errors and 6995 warnings.  (Note: Some projects may use global/workspace warnings settings.  I could change this with a patch to the org.eclipse.jdt.core.prefs files of each project.)

org.codehaus.groovy
org.codehaus.groovy.eclipse
org.codehaus.groovy.eclipse.ant
org.codehaus.groovy.eclipse.astviews
org.codehaus.groovy.eclipse.codeassist.completion
org.codehaus.groovy.eclipse.codebrowsing
org.codehaus.groovy.eclipse.compilerResolver
org.codehaus.groovy.eclipse.core
org.codehaus.groovy.eclipse.dsl
org.codehaus.groovy.eclipse.quickfix
org.codehaus.groovy.eclipse.refactoring
org.codehaus.groovy.eclipse.ui
org.codehaus.groovy16
org.codehaus.groovy18
org.codehaus.groovy20
org.codehaus.groovy21
org.codehaus.groovy22
org.codehaus.groovy23
org.codehaus.groovy24
org.eclipse.jdt.core
org.eclipse.jdt.groovy.core

Running each test project as directed (right-click on project and choose Run As > JUnit Plug-in Test) gives the following results (noted for each project).

org.codehaus.groovy.alltests  ...
org.codehaus.groovy.eclipse.codeassist.completion.test  ...
org.codehaus.groovy.eclipse.codebrowsing.test  ...
org.codehaus.groovy.eclipse.core.test  (err: 0, fail: 1 of 391)
org.codehaus.groovy.eclipse.dsl.tests  (err: 4, fail: 1 of 473)
org.codehaus.groovy.eclipse.junit.test  (err: 0, fail: 1 of 40)
org.codehaus.groovy.eclipse.quickfix.test  (err:2, fail: 2 of 240)
org.codehaus.groovy.eclipse.refactoring.test  (err: 10, fail: 10 of 704)
org.codehaus.groovy.eclipse.tests  (err: 1, fail: 5 of 606)
org.codehaus.groovy20.tests  (err: 2, fail: 7 of 801)
org.codehaus.groovy21.tests  (err: 2, fail: 7 of 801)
org.eclipse.jdt.groovy.core.tests.builder  (err: 19, fail: 30 of 1496)
org.eclipse.jdt.groovy.core.tests.compiler  (err: 17, fail: 12170 of 76923)

**Comment by hammenb** [comment]
@eric-milles I've made updates based on your feedback. [See the two latest commits](https://github.com/hammenb/groovy-eclipse-wiki/commits/master).

**Comment by eric-milles** [comment]
How much backwards compatibility is guaranteed by the project?  I see most core plug-ins target a Java 5 runtime.  However, the compilerResolver plug-in requires Java 6.  Is it possible to run any of this in an Eclipse with Java 5 still?  If not, could the plug-ins be upped to Java 6 as a minimum?

**Comment by hammenb** [comment]
>How much backwards compatibility is guaranteed by the project?

This table might be helpful for making that decision.  It lists all Eclipse versions currently supported by Groovy-Eclipse.

| Eclipse Release | Year | Java |
|---|---|---|
| 3.7 | 2011  | 5, 6 |
| 4.2 | 2012 | 6,7 |
| 4.3 | 2013 | 6,7 |
| 4.3 (SR2 Java 8) | 2013 | 8 |
| 4.4 | 2014 | 7,8 |
| 4.5 | 2015 | 7,8 |
| 4.6 | 2016 | 8 |

This seems excessive.  The minimum could be increased to Java 7 while still providing a lot of backwards compatibility.

Hopefully one of the project leads will give us clear direction on what Groovy and Eclipse versions can be dropped, and which must be retained.

**Comment by eric-milles** [comment]
Do you have a similar table for Groovy versions?  1.6, 1.7 and 1.8 could be retired.  You could always use an older version of the plug-ins to work with Groovy 1.

**Comment by hammenb** [comment]
[Here are the Java requirements for Groovy](http://groovy-lang.org/download.html#requirements).

Java 5 is supported for Groovy 2.0.  Java 5 is dropped starting with Groovy 2.3.

**Comment by felixdo** [comment]
From my experience, people who want support for Java 5 and 6 are industry corporations full of money that want everything for free and give nothing back. I'd drop everything below Java 7 or even 8.

**Comment by eric-milles** [comment]
I suppose it still makes sense to run Eclipse on Java 6/7 but build projects that use Java 5.

**Comment by hammenb** [comment]
The last update to Java 5 from Oracle was 7 years ago--it's dead.  Java 6 is still receiving updates, but that's only because the end-of-life date keeps getting pushed back the original deadline.

So the question is whether or not to support the niche case where someone wants to upgrade to a newer version of this tool to develop something for an old system where it's not acceptable to also update the JRE.

I have to agree with @felixdo that catering to that narrow group of users probably will not do anything to help grow the Groovy-Eclipse user base, or the community contributing back to the project.

**Comment by eric-milles** [comment]
That seems reasonable to me. I'm in favor of creating a 3.0.0 branch where the outdated projects (and Groovy versions) are dropped.  From there, we can set Java 7 and the minimum Eclipse runtime.  And start fixing up warnings and tests and issues.

**Comment by eric-milles** [comment]
Another note on the setup instructions.  These projects come from the attic dir, which is not immediately obvious when importing and probably should not be in the default workspace:

org.codehaus.groovy
org.codehaus.groovy16

@aclement I have a few very small changes that fix up some test base classes to be abstract and make some minor project corrections.  Could I submit these as a patch for now?  I'm not quite ready to go all in on forking, branching and pull requesting.

**Comment by wodencafe** [comment]
Hi guys, I am a Java / Groovy developer and I would like to help too.

Where should I get started as far as fixing / debugging issues? Just go to the issues list?

**Comment by eric-milles** [comment]
@hammenb one thing I have discovered is that the tests are actually organized by a number of JUnit 3 test suites.  So, it is not a good idea to run entire projects or source folders as tests.  In the alltests project, there are GroovyJDTTests (for the compiler stuff) and AllGroovyTests (for the IDE stuff).  There is also AllGroovyAndJDTTests which runs the previous two in one step.

@wodencafe you could look at the setup document linked here that is proposed to replace the current PDF embedded in the project (under the docs directory).  I'd like to know if others are able to get the project setup and the tests running successfully.  From there, I'd say addressing any currently failing tests is the next best thing to tackle.

**Comment by aclement** [comment]
Sorry I'm not very responsive, i don't get time to look at this project very much anymore. Going back to questions aimed at me.

Sure, we can move the documentation into the project. I wouldn't bother spending much effort integrating it with eclipse help as I've never met anyone that uses eclipse help but if it is very little effort to do a small integration, fine.

Raising Java minimal requirements to at least 1.7 seems fine to, i might even go for 1.8

My memory on this isn't good but if things are in the attic it is because they are retired. There should be no reason to pull things out of there to get tests to pass or anything.

Patches are fine instead of PRs. I'm just not 100% on how we handle CLAs, on one hand my team doesn't really work on this code anymore but on the other it is nice to keep the IP of the project clean by having submissions under a valid CLA. I suppose we could use the spring/pivotal one here: https://cla.pivotal.io/sign/spring .

**Comment by eric-milles** [comment]
@aclement Thanks for the response.  I'd really like to get a pipeline of changes going so I can fix some of the more troublesome bugs for myself (and my organization).  I have sent in a few Pull Requests already but have been holding off on some additional changes until I can see that they will get picked up, reviewed and merged.

Would you be able to check with your organization to see if they still retain ownership of this project?  If they don't, there are already a bunch of ASL2 copyright notices on the sources.  This seems like a reasonable license to apply.

Also, has the mailing list for this project been moved anywhere?  I tried looking for it but only found archives.  I've found it very difficult to get in touch with anyone besides posting here in the Issues list.

**Comment by hammenb** [comment]
>Sure, we can move the documentation into the project.

@aclement See the pull request linked above.

**Comment by eric-milles** [comment]
@hammenb One additional note for the setup instructions:  I was able to get a suitable dev env using the Eclipse Platform Runtime Binary plus these components from the Neon download site:
- Eclipse Git Team Provider
- Eclipse JDT Plug-in Developer Resources
- Eclipse PDE Plug-in Developer Resources
- Eclipse Platform Plug-in Developer Resources
- API Tools Execution Environment Descriptions

**Comment by KrzysztofKowalczyk** [comment]
Can you all join https://groovycommunity.com/ so we can create slack channel there for groovy-eclipse ?

**Comment by eric-milles** [comment]
I've joined and created the channel "eclipse".
