### ISSUE TITLE
Missing source folders are added to classpath

### ISSUE THREAD

**Issue by dsyer** [groovy/groovy-eclipse#186]
So Eclipse moans constantly about missing source folders (src/main/groovy for example when Groovy is only being used for tests). It looks like this connector is adding stuff to the .classpath for folders that don't exist.

**Comment by kdvolder** [comment]
A sample project would really help. I beleave there's a many different ways to configure the greclipse compiler via pom. So knowing exactly what a project exhibiting this problem looks like would be nice.

**Comment by kdvolder** [comment]
I've created a sample project in the following way:

1. Use initializr (aka New Spring Starter Project) Wizard to create a spring-boot + groovy project.
2. Delete the source/main/groovy folder

The error then appears. The error does not get fixed by refreshing maven project or even deleting project, all project eclipse metadata and reimporting.

Then I also tested if perhaps we could just remove some of the goals from the pom (i,e, the ones related to 'src/main/groovy' like 'addSources', 'generateStubs' and 'compile'. I did this as it seems reasonable that if project is only using groovy in test it would not have those goals.

Even after that, the error persists. So there is definitely something wrong here.

**Comment by dsyer** [comment]
All of the samples here: https://github.com/spring-cloud/spring-cloud-contract/tree/master/samples. I had to put ".empty" files in `src/main/groovy` to make them behave. You don't need any of the dependencies. Just copy the rest of the pom.

**Comment by kdvolder** [comment]
Thanks that gives me a set of test samples to work with and make sure it behaves.

**Comment by kdvolder** [comment]
This is the bit that matters:

			<plugin>
					<groupId>org.codehaus.gmavenplus</groupId>
					<artifactId>gmavenplus-plugin</artifactId>
					<version>1.5</version>
					<executions>
						<execution>
							<goals>
								<goal>testCompile</goal>
							</goals>
						</execution>
					</executions>


Interesting... when I make a project with this kind of config it does NOT add the groovy sources folder. So it principle these project should work fine.

What I do see however is that the gmavenplus-based configurator never removes the paths when they are already there. So if the eclipse metadata was already present in the projects, then even after remove 'compile' (and related) goals, the main groovy source folder will not be removed.

If its manually removed however it stays gone upon refresh. Same if we delete the metadata and reimport project.

I'll make some adjustments to how this works so that:
 
a) source folders with paths controlled by the configurator are removed if their respective goals are missing.

b) source folders that do not actually exist will never be added.

That should make doubly sure this works correctly.

**Comment by kdvolder** [comment]
@dsyer You can try updating the m2e configurator from snapshot site. Fix should be there now.

http:://dist.springsource.org/snapshot/GRECLIPSE/e4.6/

**Comment by reckart** [comment]
Is this fix also included in 2.9.2.xx-201607251752-e45 ?

**Comment by kdvolder** [comment]
Probably not. The e45 build has not run to completion in a long time:
https://build.spring.io/browse/GRECLIPSE-GE45

**Comment by reckart** [comment]
@kdvolder well, that snapshot build needs to have come from somewhere. It includes a timestamp. So somebody seems to have run a successful build on 2016-07-25 at 17:52, right? If it wasn't the build system, then maybe somebody did a local build and uploaded that?

**Comment by kdvolder** [comment]
Actually inspecting the logs for snapshot build more closely. It did run to completion. Looks like the only reason for the 'red' icons in bamboo is that someone disabled the tests. Bamboo is expecting test results and can't find them and so it shows the build status as 'failed'.

So, yes, that build should include the fix.

**Comment by kdvolder** [comment]
I've updated the bamboo config for e45 build to reflect reality. I.e.
 - bamboo should not be expecting test results
 - changed name of the build to 'build and publish' instead of 'build, test and publish'.

**Comment by jjurkiewicz** [comment]
Hello,

I started looking into the commit that fixes this issue and it looks that it might have introduced an issue described in [#192.](https://github.com/groovy/groovy-eclipse/issues/192).
When I started debugging the issue in a project with gmaven plugin configured it looks that the `src/test/groovy` is getting removed from the classpath. I was trying to contribute the solution, however, I am not sure I know what exactly the logic should look like.
