### ISSUE TITLE
references to grapes not added

### ISSUE THREAD

**Issue by webczat** [groovy/groovy-eclipse#236]
Hello.

I have a groovy script with a quite large set of classes. The script uses grab to grab dependencies, but eclipse does not recognize this fact and does not reference those dependencies.

**Comment by eric-milles** [comment]
What version of the plug-in are you using?  @Grab works fine in the tests and for any scripts I have used it with.

**Comment by webczat** [comment]
@Grab works correctly, but because the libraries are not added to eclipse as references, I cannot use things like content assist on libraries that are grabbed

**Comment by eric-milles** [comment]
Okay, so @Grab is working.  Are you reporting that code completion does not work for grabbed libraries in a script?  Can you provide a specific example?

**Comment by webczat** [comment]
well, my testing suggest that code completion works for grab when you actually use the libraries in the script that does the grabbing.
However, this is not the case in classes external to the script that do not directly use grab, but that were loaded by the script.

**Comment by eric-milles** [comment]
That is the correct behavior.  If an @Grab library was added to the Project, that would make it available to all scripts and classes in the project.  That is incorrect scoping of the library, since you may define more than one script and not all may have the same grapes.

**Comment by webczat** [comment]
no no. this is like a script referencing classes. one file is a script, rest are normal classes referenced from it.

**Comment by eric-milles** [comment]
I understand that.  In that case, the expectation is that there is no compilation going on before runtime.  When the script and supporting classes are compiled, the grapes have been resolved.  All is well.  It is only during development that you are missing the content assist.  Correct?

What I am saying is there is the possibility of 2 or more scripts per project with any number of supporting classes.  Therefore, adding grapes to the project is incorrect, because the scope of project is not the proper place for the libraries which have the scope of script.

**Comment by eric-milles** [comment]
This is quite similar to the problem Eclipse has had for a long time with multiple source folders and multiple classpath containers.  You may intend for one source folder to be main sources and the other to be tests and pair a classpath container up with them accordingly.  However, Eclipse provides no means to prevent a main class from referring to a class from a test library and vice versa.  There is not enough scope control in place to make this all work.

So, if @Grab libraries were added to the visible classpath containers, we would soon get a bug that a script ran fine from Eclipse but failed on the command line because a reference was not available.

**Comment by webczat** [comment]
so how am I meant to resolve this? if my project uses few libraries, and script grabs them? and classes are not precompiled.

**Comment by eric-milles** [comment]
The only thing missing is content assist, correct?

**Comment by webczat** [comment]
it seems to me that is correct

**Comment by eric-milles** [comment]
Here are a couple possible workarounds:
1) Paste your @Grab annos into the file you are editing and need type/method lookups, then remove the annos when finished.
2) Use the Apache Ivy plug-in (very nice, highly recommended) and add your dependencies using an ivy.xml classpath container to create the same references you are looking for from the Groovy plug-in.  (I could provide an example of this if you'd like.)

**Comment by webczat** [comment]
okay, I understand you.
