### ISSUE TITLE
GroovyEditor.updateOccurenceAnnotation blocks Eclipse UI thread for no reason 

### ISSUE THREAD

**Issue by frozenspider** [groovy/groovy-eclipse#250]
I'm using Eclipse (GGTS) to work with a rather big Grails project, and from time to time it just hangs for no apparent reason for a several minutes (!). This makes Eclipse almost unbearable to use.
Last time I got enough of it, so I used Java VisualVM to investigate what's happening.

As it turned out, the culprit is `GroovyEditor.updateOccurenceAnnotation` which executes in main thread, rendering Eclipse completely unresponsive and unusable randomly for few minutes straight.

My environment details:
* Windows 8.1
* jdk1.7.0_45 x64
* GGTS 3.6.4.RELEASE with `Groovy-Eclipse Feature 2.9.2.xx-201502281941-e44`

Stuff captured with VisualVM:
* Thread dump: https://www.dropbox.com/s/nnoc72gn1p45gfq/threaddump-1482820612576.tdump?dl=0
* Snapshot: https://www.dropbox.com/s/a3tnbwkns2i83ce/1482820543313.nps?dl=0

**Comment by eric-milles** [comment]
@frozenspider Could you try to recreate with the latest Groovy-Eclipse snapshot?  There have been a lot of changes recently.  The update annotation method suggests this may be somehow related to #155.

**Comment by eric-milles** [comment]
I'm having a look at the code in question.  If you want to work around this problem without an update, you can toggle off the Mark Occurrences item in the toolbar (Alt-Shift-O).

**Comment by eric-milles** [comment]
Can you try again with the latest snapshot release?  There is nothing running in the UI thread that the Java editor does not do for the same purpose.  That being said, it does parse and partially compile the source in order to located occurrences.  This can take a couple seconds in some cases.  The GroovyOccurrencesFinder uses the CodeSelectHelper to find occurrences and the helper has been fixed up a lot recently.

**Comment by frozenspider** [comment]
Sorry for the delay, I've just returned from my vacation. Thanks, I'll try it and let you know how it performs
