### ISSUE TITLE
Bamboo CI builds need repairs

### ISSUE THREAD

**Issue by eric-milles** [groovy/groovy-eclipse#281]
@aclement Re: Bamboo CI builds:
Andy, can you check e43, e42, and e37 builds for the missing setting related to display creation?  Then, could you have the chaining set up so that only e47 and e46 builds start after commit and then e46 triggers e45 triggers e44 triggers ... on down the line?

**Comment by aclement** [comment]
I had a look and changed a few things. Let's see what happens. But do we really need quite so many versions?

**Comment by eric-milles** [comment]
As soon as we cut a 2.9.2 release, I'm prepared to drop anything older than say Mars.  And for Groovy runtime, anything before 2.4.

BTW, Could you create a new release of the Maven artifacts?  There are a bunch of issues that can be closed once a new batch compiler version is available.

**Comment by aclement** [comment]
Last time someone had a problem with that batch compiler we just told them to use gmaven, and I think I did we did some work in the eclipse/maven integration to better recognize the use of gmaven. I think the instructions are https://github.com/groovy/groovy-eclipse/wiki/Building-Maven-Batch-Compiler for anyone that wants to try it but I am not sure how up to date they are.

**Comment by eric-milles** [comment]
The instructions seem to be intended for a Pivotal employee to execute.  They make reference to the signing key and the Nexus server.  I don't think an outside developer could get past generating the artifacts intended for publication.

**Comment by aclement** [comment]
I suspected that is where it would break down. You can leave this on a todo list but I'm not sure when someone will get to it, I recall the process being horribly finicky, i've never done it myself.

**Comment by eric-milles** [comment]
@aclemet Chaining looks good. e43 build still needs display setting.

**Comment by kdvolder** [comment]
Just FYI, I think the last time these artefacts where built and pubished was before the demise of codehaus. So the nexus keys etc where for codehaus and needed to be done by someone given access to the groovy developer. So technically not a Pivotal employee but someone on the 'inside' of groovy open-source development.

If that needs to be revived it will need to find a new home since codehaus no longer exists. Probably best to talk to the folks who are currently working on groovy core to see if they are willing to host it as they did before.

**Comment by eric-milles** [comment]
@aclement @kdvolder  Would it be possible to set up a job on the Bamboo CI server to at least produce the signed artifacts?  That is, automate everything prior to the publish to Maven Central step?

**Comment by kdvolder** [comment]
No because the process was rather manual. It has never run on a CI server.

With 'hosting' I wasn't talking about a CI job, but a place to host the artefacts themselves (maven staging repo).

The 'build' itself is manual and involves setting up an eclipse workspace, letting it build and zip up some specific pieces. 

The step of setting up the workspace is manual. Then after, the zipping and uploading to staging repo was automated.

I did this all locally on my machine, with some credentials setup in my mvn settings.xml. 

It might be possible to somehow replace the manual 'build eclipse workspace' step with an invocation of tycho to build things. Though I've never tried that.
