### ISSUE TITLE
DSLD tests are not executed for snapshot builds

### ISSUE THREAD

**Issue by felixdo** [groovy/groovy-eclipse#303]
Do you know why the build runs with -Dgreclipse.dsld.disabled=true? This causes all the DSLD tests to be skipped..

**Comment by eric-milles** [comment]
Two reasons:
1) There are still a couple DSL unit tests that need to be fixed up since the JUnit4 migration.
2) When the DSLD plug-in is enabled, there is an additional background job that runs with each compilation or addition of a source to a project.  This job often holds up indexing or cleanup.  The wait for completion of the job has not been totally worked out in all the tests and so there are a few intermittent test failures.  This was stabilized by temporarily disabling the DLSD feature and tests.

**Comment by felixdo** [comment]
Ok I might investigate. The DSLD stuff is IMO a killer feature...

**Comment by felixdo** [comment]
Eric, is this the job you're talking about? https://github.com/groovy/groovy-eclipse/blob/master/ide/org.codehaus.groovy.eclipse.dsl/src/org/codehaus/groovy/eclipse/dsl/classpath/AutoAddContainerSupport.java

**Comment by eric-milles** [comment]
No, there is a DSLDStore update that runs with each save of a groovy file.

**Comment by eric-milles** [comment]
I did fix the content assist tests that started failing due to the change in defaults of the content assist preferences.  There are a couple failures due to duplicate proposals that I disabled until I can fix that.

Also, there is a bit of code to wait for the DSLD store refresh in `org.codehaus.groovy.eclipse.test.SynchronizationUtils.waitForDSLDProcessingToComplete()`.  It may need to be added to a test suite somewhere.  I'll try a dry run with the DSL tests enabled sometime later this weekend.
