### ISSUE TITLE
Is it possible to DSLD-add a method that returns a collection containing elements of a certain type?

### ISSUE THREAD

**Issue by felixdo** [groovy/groovy-eclipse#305]
I add a method that returns a Collection<SomeType>. Can I tell the DSLD that the type is Collection\<SomeType\>, and not just Collection? I'm new to  groovy, so maybe this makes no sense...

**Comment by aeisenberg** [comment]
Sure. See an example [here](https://github.com/groovy/groovy-eclipse/blob/master/base/org.codehaus.groovy25/plugin_dsld_support/dsld/DSLD_meta_script.dsld#L172). You can specify something like `property name: 'myProp', type: 'java.util.Collection<String>'` to mean a property whose type is a collection that contains string elements. Note that the type needs to be stringified and that the fully qualified type name needs to be used. We need to use strings since type parameters are erased at runtime and this is the best way to keep this information around.

**Comment by felixdo** [comment]
Ok thank you. I'll maybe add some of my examples to the wiki.

**Comment by aeisenberg** [comment]
I think that would be very useful.
