### ISSUE TITLE
Step over continues to next breakpoint

### ISSUE THREAD

**Issue by felixdo** [groovy/groovy-eclipse#312]
I have GroovyEclipse installed and I am debugging a JUnit4 Plugin Test which launches a script through a GroovyShell. I have a breakpoint where execution stops. When I press "Step Over", i expect execution to halt at the next line, but that doesn't happen. Instead, execution just continues. Is this groovy-eclipse/jdt patch related maybe?

**Comment by eric-milles** [comment]
I've been poking away at this since I have experienced similar behavior.  Best I can tell, Eclipse is communicating with the runtime process (the thing being debugged) and some requests for "this" in a given scope are failing.  These failures break down the checks for breakpoints and stepping.

Here is my recreation scenario:
```groovy
@groovy.transform.CompileStatic
class C {
  String string
  C(String s = null) { string = s }

  static void main(args) {
    def c = new C('') // put breakpoint on this line, run as Java app, and step
    println c
  }
}
```
JDWP will get into `org.eclipse.jdi.internal.MirrorImpl.defaultReplyErrorHandler(int)` with error code 35, because `org.eclipse.jdt.internal.debug.core.model.JDIThread.StepHandler.createStepRequest(int)` fails on call to `ObjectReference thisObject = currentFrame.thisObject();` (line 2576 in Eclipse Oxygen).

**Comment by eric-milles** [comment]
I patched the issue that I discovered and filed a bug with Groovy core to do so as well.  You will need to recompile all your sources with this fix to get improved debugging.  I'm not sure if that will be enough to fix your issue, but it did help debugging and variables display for me.

**Comment by felixdo** [comment]
Can you link to the groovy core bug for completeness?

**Comment by eric-milles** [comment]
https://issues.apache.org/jira/browse/GROOVY-8289
