### ISSUE TITLE
Eclipse Oxygen can not add Groovy-plugin along with Java 9

### ISSUE THREAD

**Issue by anbusampath** [groovy/groovy-eclipse#318]
![image](https://user-images.githubusercontent.com/1268973/27859537-f906ac7a-6170-11e7-8af9-5b48aa461724.png)

**Comment by eric-milles** [comment]
Both features patch the same JDT plug-in.  Only one patch per plug-in can be made.

**Comment by reckart** [comment]
For me, the JDK 9 support installed after also upgrading to the latest Groovy plugin builds. However, after that hell broke loose and hardly anything worked anymore. No idea though if that was due to the JDK9 support itself or due to a conflict between the JDK9 and Groovy JDT patches.

A restore of the last working configuration was not possible since Eclipse claimed it could not find any repo with previous Groovy plugin builds. So I had to restore Eclipse from a backup to get it back working.

**Comment by eric-milles** [comment]
If you plan to run Eclipse itself under Java 9 with Groovy-Eclipse installed, I highly recommend enabling reflection for the Groovy compiler/runtime in your eclipse.ini -vmargs section:

```
--add-modules=ALL-SYSTEM
--add-opens java.base/java.lang=ALL-UNNAMED
--add-opens java.base/java.lang.invoke=ALL-UNNAMED
--add-opens java.base/java.lang.reflect=ALL-UNNAMED
--add-opens java.base/java.util.regex=ALL-UNNAMED
--add-opens java.base/jdk.internal.loader=ALL-UNNAMED
--illegal-access=warn|debug
```

These are also good command line defaults for your Installed JRE, so that anything launched from Eclipse using Java 9 (Groovy script, JUnit tests, etc.) will have proper Groovy runtime behavior.
