### ISSUE TITLE
Type annotations enforce visibility of properties (aka private fields)

### ISSUE THREAD

**Issue by mpiggott** [groovy/groovy-eclipse#336]
Minimal test case:

```
@SuppressWarnings(Broken.FOO)
class Broken {
  static final String FOO = 'unchecked'
}
```

Works in maven CLI builds and other IDEs

**Comment by eric-milles** [comment]
In your example, FOO is actually a property.  If you add public modifier, it is a static final field and will be inlined properly with no warnings or issues.

**Comment by mpiggott** [comment]
> In your example, FOO is actually a property.  If you add public modifier, it is a static final field and will be inlined properly with no warnings or issues.

Yep, I knew `public` removes the error but this did work in earlier versions of the Eclipse plugin (e.g. 2.9.2.xx-20150327...) and perpetually reminding (and convincing) non-Eclipse developers to use `public` instead of `package` in this particular case isn't a great solution. This is also be valid in Java.

**Comment by eric-milles** [comment]
The visibility of the property is synthetic-public (not package-private) and the visibility of the backing field is private.  You could rewrite this way and it would also work:

@SuppressWarnings(Broken.FOO)
class Broken {
  @PackageScope static final String FOO = 'unchecked'
}


Previous versions of Groovy-Eclipse did minimal processing of annotations and so there was little to no checking in scenarios like this.

**Comment by mpiggott** [comment]
@eric-milles shouldn't this match CLI behaviour? Does it really make sense for one IDE to need entirely different code?

**Comment by eric-milles** [comment]
The error is emitted by Eclipse, not the compiler.

If you leave off the modifier, you are also getting a method generated.  Do you really need getFOO() to access the constant value?  I would say it is a better practice to require developers to use public in the case of static finals.

**Comment by mpiggott** [comment]
> The error is emitted by Eclipse JDT, not the compiler.

Not sure where the error is coming from matters exactly?

**Comment by eric-milles** [comment]
Groovy-Eclipse is an integration of Groovy into the Eclipse JDT model/tooling.  All the checks you see under Window > Preferences > Java > Compiler > Errors/Warnings are above and beyond Groovyc.  There are certain gaps between this tooling and plain CLI Groovyc that simply cannot be closed due to the nature of Groovy-Eclipse.  When annotations were added to the Java model, the modifier checking became active.  But so too did null checking (@Nonnull, @Nullable, etc.) and other annotation-based features.

Core Groovy has discussed respecting private visibility but has reserved such a change for a major version.  However, static compilation likely checks visibility in this case and many others.  If you get used to treating private as private today, you will be well prepared for static compilation and future Groovy versions.
