### ISSUE TITLE
There seems to be a namespace collision problem.

### ISSUE THREAD

**Issue by gtpark210** [groovy/groovy-eclipse#355]
Hello.

I am using the Groovy-Eclipse-Compiler(2.9.2-03) library for Multi-line Strings.

In my project, Java files and groovy files exist together in the same directory. Builds use Intellij.

Due to the nature of our domain, classes like 'Character.java' and 'Map.java' have been created as UDTs.

A class that is under the same package as a UDT, Problems occur when 'CharacterHandler.groovy', 'MapHandler.groovy' refers to types such as 'Chracter', 'Map'. 
When MapHandler returns a Map type that is located in the same package, it is often mistaken for a type to be a java.util.Map unless i write a full package path.

 Character and Map correspond to 'default imports' and this seems to be a collision between UDT and 'default import'. Is this a known issue? Or is it my fault? 

I would like an answer.

**Comment by eric-milles** [comment]
If I understand correctly, you have java.util.Map and my.own.Map and when in package my.own, unqualified references to Map are coming up as java.util.Map.  I would caution you in defining types with such well known names as Map, List, String, etc.

As to the question of how should unqualified references be handled, Groovyc seems to be the gold standard.  You can create a very small test project and compile it with Groovyc to see what results.  I'm not aware of any specific stated rules on how to handle the ambiguity between same-package references and default import references.  Java specification seems to be a good fallback since Groovy tends to favor Java interoperability.

**Comment by eric-milles** [comment]
What version of the batch compiler are you using?  The compiler adapter (you mention 2.9.2-03) does not do that much and forwards to the batch compiler.

**Comment by eric-milles** [comment]
Also, do you have a specific instance where the confusion takes place (compiler error or something else)?  There are a number of places where type signatures are used in the type inferencing engine and unqualified names are tried along with fully-qualified ones.  So there is potential for mismatches.

**Comment by eric-milles** [comment]
If this is still an issue with current batch compiler, please submit a new issue with a specific test case.
