### ISSUE TITLE
`@Canonical`, `@Immutable` and `@TupleConstructor` not properly supported

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#421]
Consider this example:

```groovy
import groovy.transform.TupleConstructor

@TupleConstructor
class TestRecord  {
	String foo
	String bar
}
```

and the following Java class:

```java
public class Test {

	public static void main(String[] args) {
		TestRecord t = new TestRecord("a", "b");
		System.out.println(t.getFoo());
	}
}
```

The editor shows a compilation error on the constructor call, but not on the Project Explorer. If you run this code, it works fine at runtime, so there seems to be some discrepancy between what the compiler does and what the parser says.
The same applies if you replace `@TupleConstructor` with `@Canonical`.
However, with `@Immutable` all works fine instead!

**Comment by eric-milles** [comment]
When you open a source in the editor, that source has transforms applied to it.  However, source types that are referred to are only processed through the compiler phase conversion.  Any transform that is applied after conversion will not be visible.  This includes traits as well.

I have tried some experiments to move the referred to source types to the canonicalization phase, but there were many problems encountered.  There is a partial solution implemented in GroovyCompilationUnitDeclaration.applyEarlyTransforms that adds constructors and methods.  But since the source type is only at phase conversion, not much type information is available, so it is very difficult to support transforms like TupleConstructor.

**Comment by eric-milles** [comment]
This is the same underlying issue that is causing #175

**Comment by eric-milles** [comment]
There is also a bit of dead code in Scope.getMethod that accounts for this issue in some cases.  It has been disabled for a long time now.

```java
			// GROOVY add -- give it one more chance as the ast transform may have introduced it
			// Is this the right approach?  Requires AST transforms running before this is done.
			if (methodBinding == null) {
				methodBinding = oneLastLook(currentType, selector, argumentTypes, invocationSite);
			}

	// FIXASC (M3) currently inactive; this enables getSingleton()
	// FIXASC (M3) make this switchable as it is too damn powerful
	public MethodBinding oneLastLook(ReferenceBinding receiverType, char[] selector, TypeBinding[] argumentTypes, InvocationSite invocationSite) {
		if (false) {
		MethodBinding[] extraMethods = receiverType.getAnyExtraMethods(selector, argumentTypes);
		if (extraMethods != null && extraMethods.length > 0) {
			return extraMethods[0];
		}
		}
		return null;
	}
```

**Comment by eric-milles** [comment]
![image](https://user-images.githubusercontent.com/18193802/194720454-3be013f5-e4a5-4cfd-9789-731055eb92cb.png)

**Comment by eric-milles** [comment]
![image](https://user-images.githubusercontent.com/18193802/194721795-59f13e15-af9c-4cc3-a3c3-7c0b57f47c37.png)

Covers simple cases.  Ready to test in next snapshot build.
