### ISSUE TITLE
Add support for inner type completions on partially-qualified expressions w/o supporting import

### ISSUE THREAD

**Issue by eric-milles** [groovy/groovy-eclipse#461]
In Java editor, code assist for `Map.Ent|` results in a proposal for `java.util.Map.Entry` and application of the proposal adds an import or qualifier (depending on Content Assist preferences).  Groovy editor is missing proposals for partially-qualified names like `Map.Ent` when the supporting type name is not imported (i.e. Map is a bad example for Groovy since `java.util` is default imported).

**Comment by eric-milles** [comment]
Constructor completion is missing necessary qualifier segments.  "new Outer.Inn|" shows proposal that is missing "Outer" and completes to "new pack.Inner()" or "import pack.Inner; new Inner()".

**Comment by eric-milles** [comment]
NOTE: Groovy and Java seem to be indexed differently because `org.eclipse.jdt.internal.core.SearchableEnvironment.findConstructorDeclarations(char[], boolean, ISearchRequestor, IProgressMonitor)` is finding inner type constructors for Groovy but not Java.  This should be understood so that Groovy and provide consistent behavior.

**Comment by mauromol** [comment]
Hi Eric,
please note that when trying to verify this fix with 3.0.0.xx-201802122322-e47, I face an inconsistency which I think has its root cause in #411. I'll try to explain.
If I type: `Map.` => (pause) => `Ent` and then look at the list of suggestions (which opens automatically in this case, because I have Java | Editor | Content Assist | Enable Auto Activation option checked), `Map.Entry` is *not* available.
If, instead, I start from: `Map.Ent` (being the suggestion list closed) and hit Ctrl+Space, `Map.Entry` is completed correctly (being the only applicable suggestion, so no list is needed).

**Comment by eric-milles** [comment]
Can you open a separate issu for that?  Starting from "Map.|" there may need to be parser recovery to produce a ClassExpression in the AST so that content assist works propery.
