### ISSUE TITLE
Missing suggestions for static methods in code assist when parser recovery involved

### ISSUE THREAD

**Issue by mauromol** [groovy/groovy-eclipse#501]
Consider the following:

```groovy
package test24
import java.text.NumberFormat
class Test24 {
	static main(args) {
			NumberFormat.|
			Set<Integer> s = []
	}
}
```

Invoke code assist at "|" with Ctrl+Space and start typing `getN`: `getNumberInstance` is not shown as a suggestion. Press Esc and Ctrl+Space again: voilà!
If you remove the following line (`Set<Integer> s = []`), code assist works fine from the beginning.

**Comment by eric-milles** [comment]
Because of optional semicolons in Groovy, you are completing on the expression `NumberFormat.|Set<Integer> ...` which parses much differently than `NumberFormat.|` followed by semicolon or `}` or a keyword like `if`.  If you want to insert in the middle of a section of code, starting with a semicolon and then adding any partial stuff should give you completion similar to end of block editing.

**Comment by eric-milles** [comment]
Ready to test

**Comment by mauromol** [comment]
Tested with 3.1.0.xx-201808212342-e47, but it does not work as expected. In the exact case I attached here, when invoking Ctrl+Space at `NumberFormat.|`, I just get `NumberFormat.Field` completion. If I invoke it at `NumberFormat.getN|` it works though.
However, if you hit Ctrl+Space with `NumberFormat.|;` (note the trailing semicolon), it works as expected.

**Comment by eric-milles** [comment]
Okay, yes.  I was testing without the generics on the Set declaration.  Without that, the proposals come normally.

**Comment by eric-milles** [comment]
Ready to test.  Recovery is very specific to this case; you may find other cases where it breaks down.

**Comment by mauromol** [comment]
Works well in 3.1.0.xx-201808221857-e47, thank you! 👍
