### ISSUE TITLE
Improve support for Dark Theme

### ISSUE THREAD

**Issue by eric-milles** [groovy/groovy-eclipse#666]
Eclipse has a dark theme (see *Window > Preferences > General > Appearance > Theme*).  When it is switched on, the Groovy Editor looks pretty bad; it does not auto-switch colors that are set in *Window > Preferences > Groovy > Editor.  Only the colors inherited from Java syntax coloring change.

**Comment by eric-milles** [comment]
TODO:
- auto-refresh of open editor's semantic highlighting
- semantic highlighting of Types, Type Arguyments, and Type Parameters

**Comment by mauromol** [comment]
Hi Eric, I gave a try to Photon with Dark Theme and Groovy. The default colours for Groovy editor are not quite adequate. After using "Copy Java Color Preferences" in Window | Preferences | Groovy | Editor things are much better and the feeling seems to be the same as the one given by the Java editor.
The most visible problem is that class names are black (on a dark grey background), but that's not the only problem. 
I don't know how Eclipse theme support works, but maybe you may just dynamically inherit colours from the Java editor by default, unless the user overrides them?

**Comment by eric-milles** [comment]
@mauromol I added css for the color switching in the most recent commit on this thread.  When you have an open editor, the colors may not change over 100%, but after restart you should not need to alter Window > Preferences > Groovy > Editor colors.  But in case those colors don't change over, I did fix the copy from Java so that the bold pref is copied as well.

**Comment by mauromol** [comment]
Hi Eric, I just updated to 3.1.0.xx-201808130148-e48 and tried to go to Window | Preferences | Groovy | Editor and hit "Restore defaults". Without any restart, keyword and other colours are set to purple (rather than orange), but a restart seems to fix this (otherwise a "Copy Java Color Preferences" is needed, just like you said).

Class and interfaces names are now white instead of black, so they are much more readable, however in JDT editor class names are blue (interfaces are cyan) instead. Probably the third point of your TODO list?

**Comment by mauromol** [comment]
>     * semantic highlighting of Types, Type Arguments, and Type Parameters (see #720)

Hi Eric, I guess you meant #727.
