### ISSUE TITLE
Grails method-decorating transforms impact type inferencing and syntax highlighting

### ISSUE THREAD

**Issue by kszymko** [groovy/groovy-eclipse#712]
Using:

```
import grails.gorm.transactions.NotTransactional
import grails.gorm.transactions.Transactional
```

I have groovy services (*Service) classes annotated on class level with @Transactional.
Whenever it is commented syntax highlighting works OK (ctrl click on method also works).

If I enable @Transactional on class level syntax stops working.
If I mark any method with @NotTransactional then tokens in this method are colored just fine.
Is it because Transactional has:

`
@GormASTTransformationClass(
"org.grails.datastore.gorm.transactions.transform.TransactionalTransform")
`

If so, why after creating my own TransactionalMy annotation (copy of Transactional) and annotating my services with it - it lets syntax highlighting work fine?

See screenshots and the difference on simple class:

![txoff](https://user-images.githubusercontent.com/17188530/45315688-504e4100-b535-11e8-8ac6-5afaf6e7568b.PNG)
![txon](https://user-images.githubusercontent.com/17188530/45315689-504e4100-b535-11e8-9eac-a0c1a1adb1b7.PNG)

**Comment by eric-milles** [comment]
As expected, the methods have been relocated.  The body of `m1` and `m2` have been transferred to `$tt_m1` and `$tt_m2` respectively.  The type inference visitor does not visit these new methods because they are not part of the parse result.

![grails](https://user-images.githubusercontent.com/18193802/45316583-15301b80-b4fd-11e8-9db6-82863a3e1d87.png)

**Comment by kszymko** [comment]
Tested. Finally it works as expected. 
Thank you so much Eric!
