### ISSUE TITLE
Cannot set JavaAgentClass from groovy-eclipse-batch

### ISSUE THREAD

**Issue by kota65535** [groovy/groovy-eclipse#783]
Currently groovy-eclipse-batch has no option to set  `javaAgentClass` of `GroovyEclipseCompiler`, which can be set by Groovy Eclipse Maven plugin.
This option is necessary for IntelliJ IDEA users to compile sources annotated with Lombok.

**Comment by eric-milles** [comment]
Config from Maven works like this: https://github.com/groovy/groovy-eclipse/wiki/Groovy-Eclipse-Maven-plugin#project-lombok

The `javaAgentClass` element value is passed to the forked JVM via the `-javaagent:` command-line argument.  That is why `<fork>true</fork>` is required.

For batch compilation within IntelliJ IDEA, you can do a similar thing.  That is, have the batch compiler run in a separate JVM and pass the java agent class to that JVM.  Otherwise, there are listed here all the Annotation Processing command-line options that the batch compiler supports (near the bottom below Debug Options and above Advanced Options): https://help.eclipse.org/photon/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-using_batch_compiler.htm

**Comment by kriegaex** [comment]
> For batch compilation within IntelliJ IDEA, you can do a similar thing. That is, have the batch compiler run in a separate JVM and pass the java agent class to that JVM.

Yeah, we all would love to as IntelliJ users, but how? The batch compiler does run in a separate JVM, but there is no way to configure any additional JVM parameters from IDEA. So I cannot do "a similar thing" if there is no way to set the Java agent.

BTW, passing through the value of `javaAgentClass` to `-javaagent:` is impossible because the former contains a class name, the latter a file system path to a JAR file. So in the Maven plugin there must be some intermediary step to convert one into the other (I did not check). Actually the agent should should know which agent class to run from its own manifest. How you do the reverse transformation, I do not know. Is it hard-coded somewhere or do you directly inspect JAR manifests? Would be interesting to  know, even though here it is unrelated to the solution.

I think I will open a ticket for IDEA to permit setting a Java agent.

**Comment by kriegaex** [comment]
@eric-milles, another idea is to optionally allow the batch compiler to hot-attach an agent instead of requiring a forked JVM with `javaagent:`. Of course that requires the attach API to be active on Java 9+ and an `agentmain` method + correctly configured manifest. But it would allow activating this mode via batch compiler parameter instead of via JVM parameter. Is this an option you would consider implementing? If so, I can create an issue for it.

**Comment by eric-milles** [comment]
The agent stuff is part of JVM not compiler correct?  If IDEA is forking a JVM process to run groovy compilation, it can send agent command line args.  If it is not, then does JVM support "hot attach" of agent?

If the larger goal is to get lombok to work along with groovy, there has been some progress on this front: https://github.com/rzwitserloot/lombok/pull/2643

There is a sample project that demonstrates lombok compatibility: https://github.com/groovy/groovy-eclipse/tree/master/extras/groovy-eclipse-compiler-tests/src/it/apt-lombok  Is it the agent property that is missing from your IDEA setup?  Has the working maven project been shown to JetBrains?  They should be able to support a pretty standard maven scenario of a compiler adapter that uses provided configuration properties.

**Comment by kriegaex** [comment]
> The agent stuff is part of JVM not compiler correct?

Correct.

> If IDEA is forking a JVM process to run groovy compilation, it can send agent command line args.

I was just assuming that it does fork, but that was actually a good question. I watches in a task manager while recompiling single files, both with Javac and Groovy-Eclipse. Yes, IDEA does fork. As mentioned in the IDEA issue I created and as you can see in the screenshot I attached there, currently there is no way for users to specify JVM options for the forked VM running the compiler.

> If it is not, then does JVM support "hot attach" of agent?

If you have any questions about how to implement hot attach, I have written multiple Java agents for JVMs 8 and 9+ and know how to implement hot attachment, at least for Oracle JVM or OpenJDK, respectively. References for self-study:
  * https://docs.oracle.com/javase/8/docs/technotes/guides/attach/index.html
  * https://www.eclipse.org/openj9/docs/attachapi/ (I just googled it, didn't read that one)
  * https://www.baeldung.com/java-instrumentation

Hot attachment can be implemented manually or you can use a tiny tool called `net.bytebuddy:byte-buddy-agent` in order to assist you with it. Despite the name, it does not include ByteBuddy, it is just provided as an independent helper by its author, so it is very small. It pretty much knows and tries all possible ways to auto-attach to the JVM it is currently running in, which is our use case. I am not talking about attaching to another JVM, which is also possible. It is also aware of differences between Java 8 and 9+ JVMs.

> If the larger goal is to get lombok to work along with groovy, there has been some progress on this front: [rzwitserloot/lombok#2643](https://github.com/rzwitserloot/lombok/pull/2643)

Thanks for the resource. I was actually just focusing on using Groovy-Eclipse as a Java compiler for now.

> There is a sample project that demonstrates lombok compatibility: https://github.com/groovy/groovy-eclipse/tree/master/extras/groovy-eclipse-compiler-tests/src/it/apt-lombok Is it the agent property that is missing from your IDEA setup?

Yes, again see my IDEA ticket.

> Has the working maven project been shown to JetBrains? They should be able to support a pretty standard maven scenario of a compiler adapter that uses provided configuration properties.

That is a good idea, thanks for the suggestion. So far I did not provide them with a sample Maven project but asked for an option (input field) to set JVM parameters for GrEclipse. Adding support for same to the Lombok plugin would be a next step in order to get correctly configured Maven projects auto-imported with the right JVM parameters set.

**Comment by eric-milles** [comment]
One option is for IDEA to let you put "-J" options in the compiler command line input field and they take those and move them into the JVM argument position with "-J" stripped off.  This is how javac supports JVM arguments and the batch compiler lists these as accepted but ignored.

https://docs.oracle.com/en/java/javase/13/docs/specs/man/javac.html
https://help.eclipse.org/photon/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-using_batch_compiler.htm

**Comment by kriegaex** [comment]
That would be horrible UX-wise, utterly counterintuitive. It would make much more sense for ECJ to actually support the parameter instead of ignoring it. Anyway, I think if at Eclipse nobody wants to do anything in order to improve the situation, I hope that at least JetBrains adds a new input field for JVM arguments.
