### ISSUE TITLE
2 phase compilation option for groovy-eclipse-batch

### ISSUE THREAD

**Issue by kota65535** [groovy/groovy-eclipse#824]
I'm working on a project with mixed Java and Groovy sources, and hitting the same problem with many existing issues like #704, which is related to the AST transformation.
It is known that the one of the workarounds is 2 phase compilation as mentioned at https://github.com/groovy/groovy-eclipse/issues/704#issuecomment-418746990, so I have tried and succeeded to build my maven project with mixed Java/Groovy sources by configuring 2 phase compilation, which at first compiles sources with ignoring any error, and then compiles the rest of the sources (without error).

This is my sample project: https://github.com/kota65535/GroovyEclipseTest

Configuring 2 phase compilation is quite cumbersome (requires 94 lines in pom!). So my suggestion is to add groovy-eclipse-batch an option for 2 phase compilation that does the same as above. I know this is not a elegant way, but it provides the practical way to build mixed Java/Groovy project for now.

**Comment by eric-milles** [comment]
What about a maven archetype for this?  The project's archetype is a bit old, but could be refreshed: https://github.com/groovy/groovy-eclipse/tree/master/extras/groovy-eclipse-quickstart

**Comment by eric-milles** [comment]
There are a number of approaches for solving this issue in Maven.  You can take multiple passes with the compiler as you have done.  With each pass, the expectation is that class files will replace unresolvable source references.

You can also split your dependencies between main and test source folders, which has a natural two-phase compilation within Maven and Eclipse (since 4.8).

Also, you can create sub-projects for the part of your codebase that makes use of AST transforms.

Since none of these address the root issue, I am reluctant to add something only to groovy-eclipse-batch.  Interoperability between Groovy and Java sources has historically been difficult once AST transforms come into play.  Groovy-Eclipse only resolves source references within the same project through the conversion phase.  This means most AST transforms are not executed.  I have been researching this and running some experiments to move source references through canonicalization.  However, when circular dependencies exist, this has proven difficult to achieve.

**Comment by kota65535** [comment]
> Groovy-Eclipse only resolves source references within the same project through the conversion phase. This means most AST transforms are not executed.
Sorry, could you elaborate this? Is there any AST transformation that cannot be used even if we use 2 phase compilation?

**Comment by eric-milles** [comment]
In a single execution of the batch compiler (one "phase" in your above scheme), the compiler iterates through each source in the compilation unit.  Each source is processed through all phases of compilation.  During type resolution, any other source type that is referenced is processed through the initial phases (parsing and conversion) to get a model of the type.  This is similar to how groovyc generates stubs for the groovy types.

Most of your typical AST transforms are part of the semantic analysis or canonicalization compiler phases.  Since a source reference is not processed to these phases, the transforms are not applied and so the model lacks the additional fields and methods added by the transforms.

If the compiler would expand the model data for a given source reference, there would be no need for multiple passes of the compiler.  This would benefit the batch compiler, the source editor, refactorings, etc.  There have been some attempts to add to the model.  Groovy object and property methods are still added this way: https://github.com/groovy/groovy-eclipse/blob/master/base/org.eclipse.jdt.groovy.core/src/org/codehaus/jdt/groovy/internal/compiler/ast/GroovyClassScope.java#L100

**Comment by kota65535** [comment]
Thank you for your elaborated explanation. I'm going to write a tiny wrapper tool for 2 phase compilation for now, and wait the joint compilation problem will ideally resolved.

**Comment by eric-milles** [comment]
You could also migrate your compiler setup to a parent pom that can be shared by many projects.
