### ISSUE TITLE
Cannot create new Groovy Types

### ISSUE THREAD

**Issue by Sitheps** [groovy/groovy-eclipse#828]
**Issue:**
 I cannot create or run any groovy Types at all within Eclipse. All I get is the following error when I attempt to create a new Groovy Type in my project:  "Creation of Element failed. org/codehaus/groovy/antlr/GroovyTokenTypeBridge"
(I'am also a but confused by its called Groovy Type and not Class in Eclipse GUI).

**Steps-To-Reproduce.**
1. Go to Help > Install New Software > input https://dist.springsource.org/release/GRECLIPSE/e4.8  
2. Install.
3. Get the following message "Cannot perform operation. Computing alternative solutions..."
4. Install completes, reboot Eclipse.
5. New > Groovy Project
6. New > Groovy Type
7. Attempt to open Groovy Type so start writting Groovy.
8. Error message: "Creation of Element failed. org/codehaus/groovy/antlr/GroovyTokenTypeBridge" followed by sadness. 

Setup:
- Win7
- Eclipse Photon Release (4.8.0)
- Eclipse Java Development Tools 4.7

I'm somewhat new to Groovy and Eclipse, so maybe I've missed a step or something?

**Comment by eric-milles** [comment]
@Sitheps It's call "New Groovy Type" because there are several choices including class, script, trait, etc.

This is the out-of-the-ordinary part: Error message: "Creation of Element failed. org/codehaus/groovy/antlr/GroovyTokenTypeBridge" followed by sadness.

That should not happen if JDT and GDT are aligned.  I think JDT 4.7 is misaligned with Eclipse 4.8.  You can re-install from platform binary or get a jumpstart by using Eclipse IDE for Java Developers: https://www.eclipse.org/downloads/packages/release/photon/r/eclipse-ide-java-developers

Also, Eclipse 4.10 is the current with 4.11 set to be released in the next few days.  Not sure if 4.8 (photon) is a specific requirement of yours.

**Comment by Sitheps** [comment]
Thank you @eric-milles ! 
I've elected to just install a fresh Eclipse (4.10) per your recommendation and I can now create Groove Type-Scripts and run them successfully.

Thanks again for your quick and helpful reply.
