### ISSUE TITLE
SC: search for references of Groovy property as part of path expression finds 1 exact and 1 potential match for same location

### ISSUE THREAD

**Issue by eric-milles** [groovy/groovy-eclipse#937]
Split from #935

[I]n our real project I find now that for very similar cases like this (i.e.: search for references of properties in a Groovy class) I get either single potential matches (like in this case) or, most of the times, 2 matches for each reference, 1 exact and 1 potential. This is an example, where I search for references of the `order` property an a class named `OrderPlacingOutcome` (which is just a simple Groovy bean like the above one, just implementing `Serializable` as the only difference):

![immagine](https://user-images.githubusercontent.com/1742494/62771280-2979f100-ba9d-11e9-98e7-50bd40a1d959.png)

**Comment by eric-milles** [comment]
> or, most of the times, 2 matches for each reference, 1 exact and 1 potential

I'll have to look more carefully at this.  But it is possible that the AST contains 2 nodes that infer to the field/property.  Static compilation often rewrites method call and property expressions in unexpected ways.

**Comment by eric-milles** [comment]
Here is a bit of the balancing act I referred to earlier.  One of the matches comes from `FieldReferenceSearchRequestor`, where this bit selects the node:
```java
        } else if (node instanceof ConstantExpression) {
            if (fieldName.equals(((ConstantExpression) node).getText())) {
                ...
                // check for "foo.bar" where "bar" refers to generated/synthetic "getBar()", "isBar()" or "setBar(...)"
                } else if (result.declaration instanceof MethodNode && (((MethodNode) result.declaration).isSynthetic())) {
```
Type inference sees a setter and the setter is synthetic (generated).


The other match comes from `MethodReferenceSearchRequestor`, which looks for accessor calls:
```java
        if (methodName.equals(((MethodNode) result.declaration).getName())) {
            if (isDeclaration || node instanceof StaticMethodCallExpression) {
                ...
            // check for non-synthetic match; SyntheticAccessorSearchRequestor matches "foo.bar" to "getBar()", etc.
            } else if (methodName.equals(node.getText()) || (isNotSynthetic(node.getText(), result.declaringType) && !skipPseudoProperties)) {
```
Type inference sees a setter and isNotSynthetic returns true because there is a supporting field.

These checks are designed to be mutually exclusive.  But there is a bit of overlap to keep rename working.

**Comment by eric-milles** [comment]
ready to test

**Comment by mauromol** [comment]
I tested this with 3.5.0.v201908101728-e1906 and now all references are shown as just one match, with no indication of "exact"/"potential", hence they must be exact, which is what I expect.

The only odd thing is that when I have for the same `OrderPlacingOutcome.order` property a match from Java code (like: `outcome.getOrder()`) the Search view shows the label "(1 match)" for it, which is strange because usually the number of occurrences is shown only when the number of matches is >1. See this screenshot:

![immagine](https://user-images.githubusercontent.com/1742494/62852880-08a6db00-bceb-11e9-86c2-6c09c37521f5.png)

I don't think it's an issue, however, so I'm closing this, thank you!

**Comment by mauromol** [comment]
Ouch, I can't close because you are the opener.
